### PR TITLE
need add compiler options

### PR DESCRIPTION
**Pull request by tangkingchun**
add_definitions( " -std=c++11" )

### CODE REVIEW

**Comment by Kojoley** [comment]
This is completely wrong way to do this, because it's not compiler aware. And this is already done. AMQP-CPP for this purpose uses `set_cxx_norm.cmake`. Pay attention to the following lines in the root `CMakeLists.txt`
```CMake
# ensure c++11 on all compilers
include(set_cxx_norm.cmake)
set_cxx_norm (${CXX_NORM_CXX11})
```

Btw with CMake 3.1 it can be achieved as follow:
```CMake
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

**Comment by EmielBruijntjes** [comment]
I dont know how this CMakefile stuff works, because I always use the regular Makefile. Should I merge this, or forget about it?

**Comment by Kojoley** [comment]
I'll suggest not to merge this but replace `set_cxx_norm.cmake` with something like this

```CMake
# enable c++11
if(MSVC)
  if(MSVC_VERSION LESS 1800)
    # https://msdn.microsoft.com/en-US/library/hh567368.aspx
    message(FATAL_ERROR "Visual Studio 2015 is required for constexpr")
  else()
    # do nothing as Visual Studio have enabled C++11 by default
  endif()
elseif(CMAKE_VERSION VERSION_LESS "3.1")
  if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU" OR
      "${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
    if (NOT ("${CMAKE_CXX_FLAGS}" MATCHES "-std=c\\+\\+0x" OR
             "${CMAKE_CXX_FLAGS}" MATCHES "-std=gnu\\+\\+0x" OR
             "${CMAKE_CXX_FLAGS}" MATCHES "-std=c\\+\\+11" OR
             "${CMAKE_CXX_FLAGS}" MATCHES "-std=gnu\\+\\+11"))
      if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS "4.7")
          set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
        else()
          set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
        endif()
      else()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
      endif()
    endif()
  endif()
else()
  set(CMAKE_CXX_STANDARD 11)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif()
```

**Comment by soloveyhappy** [comment]
First of all thx for a great job. I have one questionIs it posible to build project using MinGW? I had some problems with posix sockets and netdb lib.

**Comment by Kojoley** [comment]
@soloveyhappy yes, but with some changes (details here #41) and not a mainstream version (because of `TcpConnection` which uses POSIX sockets as you already noticed).

**Comment by surgura** [comment]
I think we fixed this as of 91c4f891590c630df4f2a18e3f5925ddf41b3d3f. We now require CMake `VERSION 3.1` so we can use `set (CMAKE_CXX_STANDARD 11)`.

**Pull request closed without merging**
