### PR TITLE
Add Publisher Confirms support

### PR DESCRIPTION
**Pull request by mgibula**
Hi,
this is my proposal for adding publisher confirms support to amqp-cpp. 

It adds two new callbacks (onAck and onNack) and two new methods (setConfirmMode and messageCounter) to Channel class. Rest is just new frame types. That seemed to be the least invasive solution without changing publish() return type.

Lightly tested ;)

### CODE REVIEW

**Comment by mgibula** [comment]
@EmielBruijntjes - any chance of reviewing this approach? Or would you prefer different API for this?

**Comment by EmielBruijntjes** [comment]
Sorry, I've not had the time to dive into this. I hope to do this soon.

**Comment by mgibula** [comment]
Rebased with current master

**Comment by mgibula** [comment]
FWIW, I've been using this in production for a long time, with no problems.

**Comment by pabigot** [comment]
I second the desire to see this reviewed/merged.  IMO the implementation is clean and consistent, and initial tests in my development branch look good.

**Comment by mgibula** [comment]
Yes, I'll do it, just need to find some time.

**Comment by EmielBruijntjes** [comment]
@mgibula Wonderful. You've completely followed the coding style of the rest of the library, I am massively impressed! Great job, and a great joy to merge.

**Comment by mgibula** [comment]
Thank you, and thank you for your excellent library:-)

**Pull request merged**
